"use client"
import { Inter } from "next/font/google";
import "../../app/globals.css";
import { useState } from "react";
import { MdOutlineLogout } from "react-icons/md";
import { Provider } from "react-redux";
import { store } from "./store/store";
import { toast, ToastContainer } from "react-toastify";
import { useRouter } from "next/navigation";
import Sidebar from "@/components/Sidebar";
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const metadata = {
  title: "Egeeks CMS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [showModal, setShowModal] = useState(false);

  const router =useRouter()
  const handleModal = () => {
    setShowModal(!showModal);
  };


  // log out
  const handleLogout = () => {
    try {
      // implement logout logic here
      localStorage.setItem("isLoggedIn", JSON.stringify(false));
      toast.success("Logged out successfully!");
      setShowModal(false);

      setTimeout(() => {
        router.push("/");
      }, 2000); // Redirect after showing toast
    } catch (error) {
      toast.error("Logout failed. Try again!")
    }
  }
  return (
        <Provider store={store}>
          <div className="flex">
            {/* Sidebar (Full height) */}
            <Sidebar handleModal={handleModal} />

            {/* Main Content Wrapper (Header + Content) */}
            <div className="flex-1 absolute w-full lg:left-[224px] lg:w-[calc(100%-244px)] flex flex-col">
              {/* Header (Only on Main Content) */}
              
              {/* Main Content */}
              <main className="flex-1">{children}</main>
            </div>
          </div>
          {showModal && (
            <div className="fixed inset-0 flex items-center justify-center bg-black bg-opacity-50 z-50">
              <div className="bg-white p-6 rounded-lg shadow-lg w-96 relative">

                <div>
                  <h1 className="flex items-center text-2xl text-red gap-4"> <MdOutlineLogout /> Log out</h1>
                  <p className="mt-3">Are you sure you want to Log out?</p>
                </div>
                <div className="flex justify-end items-center gap-2 py-4 px-5">
                  <button
                    className="w-[114px] h-[39px] bg-blck text-white rounded-lg"
                    onClick={handleModal}
                  >
                    Close Modal
                  </button>
                  <button className="bg-red text-white w-[114px] h-[39px] rounded-lg" onClick={handleLogout}>Log Out</button>
                </div>
              </div>
            </div>
          )}
           <ToastContainer position="top-right" autoClose={2000} />
        </Provider>

  );
}
